algoritmo "semnome"
// Função :
// Autor :
// Data : 17/03/2023
// Seção de Declarações 
var
Dist  : real
Litros: real
media : real
inicio
// Seção de Comandos 
   escreval("Qual a Distância percorrida?")
   leia(Dist)
   escreval("Quantos Litros de combustível consumido?")
   leia(Litros)
   media <- Dist / Litros
   escreval("Seu consumo de combustível é de",media," por Km corrido")
   
fimalgoritmo
