algoritmo "semnome"
// Função :
// Autor :
// Data : 17/03/2023
// Seção de Declarações 
var
Valor  : real
parcela: real

inicio
// Seção de Comandos
escreval("Qual o valor total do produto?")
leia(Valor)
parcela <- Valor / 5
escreval("Segue o valor das parcelas abaixo:")
escreval("1° Parcela: R$", parcela)
escreval("2° Parcela: R$", parcela)
escreval("3° Parcela: R$", parcela)
escreval("4° Parcela: R$", parcela)
escreval("5° Parcela: R$", parcela)
fimalgoritmo
