algoritmo "semnome"
// Função :
// Autor :
// Data : 24/03/2023
// Seção de Declarações 
var
num, num1, num2, num0 : inteiro
inicio
// Seção de Comandos 

num <- 1
enquanto (num <>0) faca
         escreval("Digite o valor: ")
         leia(num1)
         num <- num + 1
         num2 <- num2 + num1
         escreval(num2)
     se (num1 <= 0)entao
     fimalgoritmo
fimse
fimenquanto
fimalgoritmo
